2022-04-09 12:54:16,085 - INFO -   File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\trixi\experiment\experiment.py", line 78, in run
    self.setup()

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\run_tpc.py", line 10, in setup
    self.setup_template()

  File "D:\git\DL4H-Project\TPC-LoS-prediction\models\experiment_template.py", line 67, in setup_template
    labs_only=self.config.labs_only, no_labs=self.config.no_labs)

  File "D:\git\DL4H-Project\TPC-LoS-prediction\eICU_preprocessing\reader.py", line 26, in __init__
    self.labels = pd.read_csv(self._labels_path, index_col='patient')

  File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\pandas\io\parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)

  File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\pandas\io\parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)

  File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\pandas\io\parsers.py", line 895, in __init__
    self._make_engine(self.engine)

  File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\pandas\io\parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)

  File "C:\Users\weich\Anaconda3\envs\dl4h-project\lib\site-packages\pandas\io\parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)

  File "pandas\_libs\parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__

  File "pandas\_libs\parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source

2022-04-09 12:54:16,085 - INFO - FileNotFoundError(2, "File b'D:/git/DL4H-Project/TPC-LoS-prediction/eicu-collaborative-research-database-2.0/train/labels.csv' does not exist")
