2022-05-03 23:44:12,696 - INFO -   File "/home/ubuntu/anaconda3/envs/dl4h-project/lib/python3.7/site-packages/trixi/experiment/experiment.py", line 89, in run
    self.train(epoch=self._epoch_idx)

  File "/home/ubuntu/DL4H-Project/TPC-LoS-prediction/models/experiment_template.py", line 155, in train
    y_hat_los, y_hat_mort = self.model(padded, diagnoses, flat)

  File "/home/ubuntu/anaconda3/envs/dl4h-project/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/ubuntu/DL4H-Project/TPC-LoS-prediction/models/tpc_model.py", line 721, in forward
    return self.forward_original(X=X, diagnoses=diagnoses, flat=flat, time_before_pred=time_before_pred)

  File "/home/ubuntu/DL4H-Project/TPC-LoS-prediction/models/tpc_model.py", line 632, in forward_original
    **kwargs)

  File "/home/ubuntu/DL4H-Project/TPC-LoS-prediction/models/tpc_model.py", line 438, in temp_pointwise
    X_temp = self.temp_dropout(bn_temp(temp(X_padded)))  # B * ((F + Zt) * temp_kernels) * T

  File "/home/ubuntu/anaconda3/envs/dl4h-project/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)

  File "/home/ubuntu/anaconda3/envs/dl4h-project/lib/python3.7/site-packages/torch/nn/modules/dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)

  File "/home/ubuntu/anaconda3/envs/dl4h-project/lib/python3.7/site-packages/torch/nn/functional.py", line 1169, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)

2022-05-03 23:44:12,696 - INFO - RuntimeError('CUDA out of memory. Tried to allocate 186.00 MiB (GPU 0; 14.56 GiB total capacity; 5.63 GiB already allocated; 142.50 MiB free; 6.68 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF')
